# tap "adoptopenjdk/openjdk"
tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jandedobbeleer/oh-my-posh"
brew "readline"
# brew "python@3.10"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "bandwhich"
brew "glib"
brew "harfbuzz"
brew "bfg"
brew "boost"
brew "deno"
brew "folly"
brew "edencommon"
brew "fizz"
brew "wangle"
brew "fbthrift"
brew "fb303"
brew "guile"
brew "p11-kit"
brew "unbound"
brew "gnutls"
brew "libarchive"
brew "libbluray"
brew "srt"
brew "tesseract"
brew "ffmpeg"
brew "gcc"
brew "gh"
brew "git"
# brew "git-filter-repo"
brew "go"
brew "gobject-introspection"
brew "hdf5"
brew "shared-mime-info"
brew "libheif"
brew "libraw"
brew "imagemagick"
brew "inetutils"
brew "ios-deploy"
brew "jq"
brew "mas"
brew "mkcert"
brew "neovim"
brew "nghttp2"
brew "openssl@3"
brew "pastel"
brew "podman"
# brew "python@3.8"
# brew "r"
brew "rbenv"
brew "pyenv"
brew "nvm"
# brew "redis", restart_service: true
brew "scrcpy"
brew "thefuck"
brew "watchman"
brew "aws/tap/aws-sam-cli"
cask "postgres-unofficial"
cask "pgadmin4"
# cask "adoptopenjdk15"
# cask "android-commandlinetools"
cask "appcleaner"
cask "arc"
cask "calibre"
cask "docker"
cask "emacs"
cask "gimp"
cask "google-chrome"
cask "google-earth-pro"
cask "gpg-suite-no-mail"
cask "http-toolkit"
cask "itsycal"
cask "jumpcut"
cask "macintoshjs"
cask "michaelvillar-timer"
cask "microsoft-edge"
cask "microsoft-teams"
cask "mimestream"
cask "moom"
cask "netbeans"
cask "netnewswire"
cask "powershell"
cask "qgis"
cask "reflex"
cask "rstudio"
cask "scrivener"
cask "spotify"
cask "visual-studio-code"
cask "vlc"
cask "warp"
mas "Downlink", id: 1454269192
mas "DuckDuckGo Privacy for Safari", id: 1482920575
mas "Gifski", id: 1351639930
mas "GrandPerspective", id: 1111570163
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Simple Comic", id: 1497435571
mas "The Unarchiver", id: 425424353
mas "Vinegar", id: 1591303229
mas "Wayback Machine", id: 1472432422
mas "WorldWideWeb", id: 1621370168
mas "Xcode", id: 497799835
